/**
 * Created by ${AuthorFullName} on ${YEAR}-${MONTH}-${DAY}.<br>
 * SObject API Name: ${SObject_API_Name_eg_Opportunity} <br>
 * Selector Class Name: ${Selector_Class_Name_eg_OpportunitiesSelector} <br>
 * Selector Test Class Name: ${Selector_Test_Class_Name_eg_OpportunitiesSelectorTest} <br>
 * Selector Interface Name: ${Selector_Interface_Name_eg_IOpportunitiesSelector}
 */
 
public interface ${Selector_Interface_Name_eg_IOpportunitiesSelector}
        extends fflib_ISObjectSelector
{

}