/**
 * Created by ${AuthorFullName} on ${YEAR}-${MONTH}-${DAY}.<br>
 * SObject API Name: ${SObject_API_Name_eg_Opportunity} <br>
 * Domain SObject Class Name: ${Domain_SObject_Class_Name_eg_Opportunities} <br>
 * Domain SObject Test Class Name: ${Domain_SObject_Test_Class_Name_eg_OpportunitiesTest} <br>
 * Domain SObject Interface Name: ${Domain_SObject_Interface_Name_eg_IOpportunities} <br>
 * 3 Domain SObject Classes
 */
 
 
@IsTest
private class ${Domain_SObject_Test_Class_Name_eg_OpportunitiesTest}
{
    @IsTest
    static void testBehavior()
    {
    }
}